/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author JOSEPH TALENTOS
 */
public class Registrarse extends javax.swing.JFrame {

    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tx_usuario_re = new javax.swing.JTextField();
        tx_contraseña_re = new javax.swing.JPasswordField();
        nombre_usuario_re = new javax.swing.JLabel();
        contraseña_re = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tx_usuario_re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_usuario_reActionPerformed(evt);
            }
        });
        jPanel1.add(tx_usuario_re, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 150, -1));

        tx_contraseña_re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_contraseña_reActionPerformed(evt);
            }
        });
        jPanel1.add(tx_contraseña_re, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 150, -1));

        nombre_usuario_re.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        nombre_usuario_re.setText("Nombre de usuario:");
        jPanel1.add(nombre_usuario_re, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        contraseña_re.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        contraseña_re.setText("contraseña:");
        jPanel1.add(contraseña_re, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 70, -1));

        guardar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/user.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setText("Registro de nuevo usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 300, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/stock-vector-soft-skills-or-personal-attribute-to-be-success-confident-businessman-with-elements-of-soft-skills-2269346807.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 220));

        regresar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 490, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 489, 302));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_usuario_reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_usuario_reActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_usuario_reActionPerformed

    private void tx_contraseña_reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_contraseña_reActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_contraseña_reActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        
        //datos manual
        String usuariocorrecto="david";
    String contraseñacorrecta="2345";
    
    // capturamos usuario y contraseña
    String usuarioIngresado = tx_usuario_re.getText();
    String contraseñaIngresada = new String(tx_contraseña_re.getPassword());
  
                                              
        if(usuarioIngresado.equals(usuariocorrecto)&& contraseñaIngresada.equals(contraseñacorrecta)){
            
            // mensaje cuando se presiona el botón "Guardar"
    javax.swing.JOptionPane.showMessageDialog(this, "¡Registro de nuevo usuario guardado exitosamente!", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        Registrarse registro = new Registrarse();
        registro.setVisible(true);
        }else{
        javax.swing.JOptionPane.showMessageDialog(this, "Deseas registrarse nuevamente?", "", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        Registrarse registro = new Registrarse();
        registro.setVisible(true);
        this.setVisible(false);

        }
        
  
        
        
    }//GEN-LAST:event_guardarActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        elige_opcion regresar = new elige_opcion();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
                this.setVisible(false);
            }

            private void setVisible(boolean b) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contraseña_re;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nombre_usuario_re;
    private javax.swing.JButton regresar;
    private javax.swing.JPasswordField tx_contraseña_re;
    private javax.swing.JTextField tx_usuario_re;
    // End of variables declaration//GEN-END:variables
}
